# Generated by Django 5.1.1 on 2024-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_movie_num_votes_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(default=0),
        ),
    ]
