# Generated by Django 5.1.1 on 2024-10-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_remove_movie_genre_remove_movie_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.movie')),
            ],
        ),
    ]
